name = "mtls-ocsp"
main = "src/index.js"
compatibility_date = "2023-11-12"

workers_dev = false
routes = [{ pattern = "mtls-fw.${DOMAIN}/ocsp", zone_name = ${DOMAIN} },
{ pattern = "mtls.${DOMAIN}/ocsp", zone_name = ${DOMAIN}, }
]

[vars]
CA_CLIENT_ISSUER = ${CA_CLIENT_ISSUER}
CA_OCSP_ROOT =${CA_OCSP_ROOT}